# -*- coding: utf-8 -*-
"""PasswordGenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WwHP79hhl4uz3J3xRaLsQv5fwVzbcYIa
"""

import random
letters=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o',
         'p','q','r','s','t','u','v','w','x','y','z','A','B','C','D',
         'E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S',
         'T','U','V','W','X','Y','Z']
numbers=[0,1,2,3,4,5,6,7,8,9]
symbols=['!','@','#','$','%','&','(',')','+','[',']','/']
print("Let's Generate a password")
n_letters=int(input("How many letters do you want in your password?\n"))
n_numbers=int(input("How many numbers do you want in your password?\n"))
n_symbols=int(input("How many symbols do you want in your password?\n"))
password_list=[]
for i in range(1,n_letters+1):
  c=random.choice(letters)
  password_list.append(c)
for i in range(1,n_symbols+1):
  c=random.choice(symbols)
  password_list.append(c)
for i in range(1,n_numbers+1):
  c=random.choice(numbers)
  password_list.append(c)

random.shuffle(password_list)
password=""
for i in password_list:
  password+=str(i)

print(password)